public class DayFour {
    public static void main(String[] args) {
        int counter = 0;
        int anzahlOfSelectedChars = 142;
        int lengthOfLine = anzahlOfSelectedChars - 1;

        String inputString = "SASASMSSSMSMSMSMSSMSAMXMAMAMXSXXXMAMMXSAMXMXMXSMMMXXXSXXAXSMMMAMXAXSMSSXXMSASASMXSSMSMSXMMMAMMMXXSAMXSSMXAXSASMMMXMASAXSXMXMAMXAMXXMAXXAMAMX\n" +
                "AASAXAAAAXXASASMXSAXAMXXSMSSMSAXSMSMMASAMAAXMAMAAAMMMMMSMXSAMXSSMSMXMAXMASXAXAMXAAXMAMXAMASAMAAMXMASAMAAMSMSASASMMMMAMSXSMASMMSMSMMASMMMSAMA\n" +
                "MXMXMMMSMMMMMAMXAMXMSSSMAXAAXMAMAAAXMASASMSXMASMMXSAAAAAMAXAMAXAAXAAMXMAMXMSMSMMXMASMSMXSASAXXXSASXMASXMMXAMMMAMMAXMXMMAXXAMAAAAAAMAMAAXSAMA\n" +
                "XSMSAXMAMAAXMAMMSSXSAAXSMMXXMASMMSMSMXSMMAMMSMAAXASMSMSSSMSSMMSMMMSSSSSSSMAMAAXMXXXAAAAAMMSAMSMSASMSXMASAXSAMMSMSMMMAAMAMMSSMSMSSSMAMMSMSAMX\n" +
                "XMAMAMSASMSSSMSAXAMXMSMAXAMMMXXXXMMXMAMAMXMXAXMMMMSAMAAXAXAXMXMAMXMXAAMAAMAMXMMXMMMMMMMMSAMAMMAMAMAMASXMXMXXSAXMAAASXSMXSAAAXXAXAXXSSMMASAMM\n" +
                "XMAMAMXAMXXXMAMXMMAXAAXMXSAASAMXSMASMASAMXSXMSXSXAMAMMMSSMMSXXMASAMMMMMXXMASMMMSMMASAMASMASXMMAMASXMAMXMAMSXMXSSSSMAMAXAMMSMMSMMAMXMAAMXMMMA\n" +
                "MSASXSMSMXSAMXMMMMSMXMMMAMXMMASXXAXXMAMASASAAXAMMSSMMMXAXMAMMMXASMSASXMSSSXSAAAMAAASASXSAMSAASXXXSASMMMXAXAMMXMXMAMXSMMXXAXMAMXMXMASXMMSMASX\n" +
                "MSXMASXAAXSAMXMAXXXAMMMMASMSSMMXMXMSMSSMMASMMMAMAMAASMMMMMASMSMMSXAXSAMAAAASXMMSSMXSAMMSMMSMMMSMSMXMAASXXMAXMAXMMXMMAXXXMASMXMAMASMSASAXMAMX\n" +
                "MXMXSMSMSMSXMSXSXMAMAAAMXSXAAMSMAAAXXAAMXAXAXXXMXSMMXXASMSMSAMAXSMSMSAMMSMASXMXAAMAMASAXAAXAMAMMAMSMSMMAMSSMSXSASMMSXSXMMASMMSASASAXXMASMXSM\n" +
                "SAXMAMAXAASAMXMMASAXSMXSAMMSSMSASMSMMSSMMXSXMSAMXSAMSSMMAAAMASMMMAAMMAMXXAASXMMMMMMSAMMMMMSXMAMSAXMAAXMAMXAAASMMMXAXMMAMAXMAMMMMXSXSSMMMXAAA\n" +
                "SAMSMSMSMSMMAAMMAMAXMASMMSAMXAXXXAAMMAMXMMSMAXMMASAMASXAMMMMAAMXMSMXSAMXXMMSMXAAASXMASXXSASMSSMSXSMMMXXAMMMMMAXAMSMMASAMXSMSMXAMASAAMAAAXSMM\n" +
                "XAMMXSAAMXMASXSMXSSXMMMAMMASMMMSMSMSAMSASXSASMXMASXMASMSSMXMXSAMXXXMSXXMAAAXAMMSMSAXSMMAMASXAXMSXAAXAASMSMXAXMSAMMASXSXMAMAMXMASASMMSSMSAMXS\n" +
                "XAMXASXMSSXAXAXMAXMAAXMMMSXMAMASMAAXAXSASAMSMAXMASAMASAAAAXMAMXASMSMSMASMMSSSSMMASAMMAMXMMMMSSMMMXMMMXSAAASXSXSAXSAMAMMSSMMMAMMAMXAXAXMMAMAM\n" +
                "MSAMXXAXAMMSSMMSXXXAMXXXXXXSAMSSMXMSMMMXMMMASXXMMMXMASMMXMXMASXSXAXAXSMXAAXAAAXMAMMMXAMXSXMSAAAAMASXMMMMMMSAAAXXMMMSAXXAAAXMXXSAMSXMASMSXMAM\n" +
                "XXAXXSMMMSMAAAAMMSMAXXMMAMXSASMXMAMAASMMSASAMMMMSXXMASXSSMSMASXMMSMMMSXSMMMMSMMMXMAMSMMAXAXMASMMXAXAXMAMXMMXMMSMASAXASMSSMMMAASAMSXMAAXXMSAS\n" +
                "SSMMMSAAXAMSSMMSAXXAMXMSSSMSXMAMMSSSSMAMSAMMMSAAAMAMXSMXXAAAAXMXAMASASAMXAAXAXXXSAMXAAMXSXMSMMMXMSSXXMASMAAXXXAAMMMSAAAXAXAMAXMAMMAMMSAMXXAA\n" +
                "XAXMASMMSMXMAAXMASMMMXXXAAAXSMMMAMAMXMAMMAMAASXSMXMASXMXMSMSXSMSSSMMAXSMMSSXMSMXXMASXSMAXMXMASXSSMAMASASXMMMXSASMAXAXMSXSSMSMMMMMSXMAMMASMMM\n" +
                "SMMMASMAXXXMASMMXMASXMXMSMMMMSAMXSAMSSXMSSMMXSAAXASXMAXXAAXAXMAAAAXMMMXSAAXASXAMMXMMMAMSSMMSAMXMASMAXMASXSXAAAAAMXMMXXXMASAAXAXAAXSMASMAMAAM\n" +
                "MMMSAMMXSXMSXMASASXMAXSAMAMAAMXSXXAMMMSMAMXXSMMMSXSAMXMMSMSMMMSMMMMSMAMMMXSXMAMAMXAAMAMXMAAMAMXAAMXXMASXMSXMMMMMSMMXSAMMAMXSSSSMMMAMAXMASMMM\n" +
                "MAAXAXXXAMXMASMMAXAMAMMAMMSMXSAMXSSMSAAMAMSXMAAXXASMMAXAAXAXXXAAXSMMMASXMXSASAMSMSSSXSSMSMMMSMSMSXXXSXMXAXMMASXXXAXXXAXMXSXMAAAASMMMAMSASASA\n" +
                "MMSSSMSMSMAMXMMMSMSMSXMMMXAAAAAXAAMAMSXMASXAXSMSMMMASXMSSSSSSSMSMMAASXSMSMSASXSXAMAMXMAMMAMXXAXAAXSMAAMMXMMSASXMSSMSSMMMASAMMMMASAXSSXMASAMM\n" +
                "SAMMAMAAASMSMSAAAMMAXMSAMMMSMMMMMSMAMAMSMMXSMAAXAMSXMAAMAAAAAMSXAXSMMXMASAMAMMXMXMAMMXAMSAMSMAMXMAMAMAMSSMMMSSXAAAAMAMAMASXMASXASXMAXAMAMAMX\n" +
                "MASXAMMMMXXAMXMMXSMAMASASXXMMSSXMAXAMXXAXSAMSSMSSMXXAMMMMMMMMXSMXXAAXXXSXMMAMAXSXXXMASMMMMXAAXXSMMMSSMXXAAXMASMMXXMXAMAMASXMASMASAMMSXMMXMMX\n" +
                "XAMMXSAXXXSMSSMSMSXAMMSAMXAAAXMASMSXMXSSSMAXAXMAMMMMAMAXXXXSMAXAMSSMMMXMAXSXMSAMXSSMXSAAAMMMXSMMMAAMAAXXMMMXMXXMASMSXSMSAMXMAXAMMXMXMXMAAMSS\n" +
                "SSMMXMASMAXSAMAMAMSXSXMAMSXMXMMAMAAASAMXAAXMASXMXAAAASMSMSAAMAMSMAAAXMAMXMXAAAAXXAXMASMSXSAMMAAASMSSSMMMSSSXMMMMXXAAAMAMAMXMASXXMAAASAMMXSAM\n" +
                "XAASXSAAMAMMXMAMAMXMXMMXMSXSASMMSMSMMAASMMMMXSMMSSSSMSASAMSMXAMAMMSMSSXXAAMMMSMMMMAMXXXAASASXSMMSAXAXXAXAAMXXAAAXMSAMXAXAMMMXSMASMSMSASASMMM\n" +
                "MSMMAMSSMSSSMMXSXSSMAMXSXXAMAXAXAXAASAMXMAMXAXAAAMAAAMAMXMXMMMXAXMAAAAMSXXAMAMAXXXMMMMMXMMMMMAMAMXMAMSSMMSMSSSSSXAAXSXXSASAMAMMMMAAASMMMXASX\n" +
                "AXAMXMAMMXMAAXXAXSAMMSASMMSMMMSMMMMASMMASAMSAMMMSSXMMMXMXSXSAMSMSXMSMXMASXXMASXMAXSAAXMSXMXXSAMASXMAMAAMMAAAAAXXASXSMAMSAMMSAXAXMSMMXMASXMMX\n" +
                "SSXMAMSSMASMSMAMXSXSAMXSAAAXAAAAXXXXMAXAMAMMAMSSXMASAMXMASASMXAAXMAMXXSAMXMSMSMSMASMSSMMAAAXMXMXSXSASMMMSMMMSMMXXMMAXSMMAMAMMXSXXXMSASASMAMA\n" +
                "AMXMXMXAXASAMMSXMSAMMMAMXSMSMSSSMSSXSAMSSSMMXMXAAAASASXMASAMXSMSMASMSMMMSXMAAMAAMAXMMAASMMMSSXSASMXAXAXAXXXAAAXMASMMXMAASMSXSAXSMAASXMAXMAMX\n" +
                "MMAMAMXMMMXAXAMAAMXXAMAMAXXAAMXAASAAMXSAAASAMXMSMMASAXASAMAMXAAXMSMAXXAAAASMSMSMSMXXSMMMMXAAASMAMAXSSMMMSMMSSSMSAMXSASAMXAMAMMSASXMXXSXMSSSM\n" +
                "XSASASMXXSSMMSXSXXAMMSMSMASMSSSMMMMMMMMASAMMSAAXXXAMXMAMASMMXMXMXAMMMMMMXXMAAAAAAASMSAMMMSMMSMMXMSXMAMAMXAMXAXAMXSAMXSMSMAMMMMSMMSSXMSAXSXAX\n" +
                "ASMSASAMXXAAAMXXXMMAXAAAXAMXAAAAMXAXXAXMMASASASMXMASAMASXMAMXXAASMMAAXASXSMXMXMXMMXASMMAAAAXXXMAXMMSAMXXXAMMXMSMMMMSAMXXMAMXXXMAAAXAASXMMSXM\n" +
                "XSAMXMAXSSSMMSAMXSASXMSMMXSMMXXMASMSMMSXSXMAXAMAXMASASASMMMSSMAXAASXXSASASXMSASXSMMAMMSMSSSMSASMXXAXAMAMSSMMMMXASMSAMXAXXMASXMSMMSMMMMAXMXSA\n" +
                "MXASMSMXXAXAXMXMASMMXAAMMMMMSMAXAAMXMMSAMMMSMMMXMMXSXMAXXXAAASMMMMMAAMAMAMAXSASASMSAMXAXXXXASXMSAMSSMMMXAAXMAMXAMMXMASXSXAAXAAAXAAXMASMMMMAS\n" +
                "SMMMMAMSMXMXMXMMXSXXMSMSAMAAAMSMSMMAXMMMMMAXAXMMASAMXMMSSMMMXMXMAXMXMMSMXMXMMAMMMASXSMMMSAMXMMAXMAMAAASMSMMSSSMMMAAMMXMMMAASMMMXSAMSASAAAXSX\n" +
                "MXMAMAXAMMXMMMSAMXMSAMXSAMMSXSAAXASXMSASXMSXXMASAAMXAMXAXMAMMSMSSSMXXXAMAXASMMMAMMMMMXAASAXMXMASXSSMMMSAMXAAAXAMXSSXSASMASMMXAXXMAMMXMMSMSAM\n" +
                "SASXSMSMSAASAAMAMAMMSMXSAMXMMMMXSAMAASASAAMXMSAMXSXSSMMMSSXSAAAAAAXSMSMSSXMMAAXMMAAAXMMXSAMXMMMMMXMASXSXMMXSMSMMAXXAXMMAMMAXSMXAMAMXMAAXMMMA\n" +
                "MMSAAAXAAMMMAXSAMASAXMXMMMAAAMXAMAMMMMAXMAMXXMXSSXAAAASXAMAMMSMMMSMSAAXSAASXSMSSSXSMSXSASASMSAAASASMMAMMMXAXXAAMMSMMMAXMMSSMSASMSSXSAMASAXXS\n" +
                "SXMXMMMMMXMMXMSXSXMASMXAAMMSMSMMSXMAXMMMMASXAAASMMSMSMMASAMXAXAMXXASMMXMSAMAXAAAMMMAXMMXSAMAXXSSXXSXMAMAMMMSSMSMAXAASAMXXXMAMXMAAAAXSMMAMXXX\n" +
                "AXMXMSMMXMSSMAXAXAMAXMAMMSAMMAXXXMSMSMMXSAMXMMMMAXAXMXAAMAXMSSSXSMAMXMXXXSMAMMMXMAMMMAXXMAMMMXMXMAMXSMSASXAAMMAMSSSMMASXMSMSMSMMMMMMXMASXMXX\n" +
                "XMAMAAAXXMAAMXMMMMMMSXMSAMAMSSSXMMAMAAAAMAXAMXMXMMSMSMMSMXMXAAXAXMXMSMSMAMMSXSMXMXSAASMXMAMXMAASXSAAMXSASMMSSXMSAMMXSAMXASAMXXASMXSSXMSMAMSM\n" +
                "XMAAMXSMAMSMMXMAAXAMAAMMMMAASAMAXSMSSSMMSSSMMASAMXAAAAXAXSMMMSMSMMXMAAAMXMAXXAXMXAXXXAMXSMSMSMSMAAMASAMMMMAAXASMMXSAMXSMSMMMSSXMXAXMAMAMAMAA\n" +
                "MSMXSAAMMMMAMAAXXSASMXMASMXSXAMSMMAAMXAAAMAASASASXMSMXMMXAAAXMAXAMSSMMMMMMXSXMMSMMSMSAMXXMAXMXMMMMMAMMXSAMMSSMMAXXXXMMMMXAAAXMAXMAXSMMXSSSMS\n" +
                "AAAAMMSMSASAMXXSAMAXXXSASXMMMMMAAMMMSSMMSMSMMAXAMXXMMMAXXSSMSMASAMXASAXXASMMMMAAAXAXMXMXXSXSXMXMASMXSXASASAMAXMSMSMSAAAASXMXSSXMASMAASAMXMXM\n" +
                "SMSMXAMXMASXMAXMAMMMMXMAXAXXAMSXMMMXAAMXMAAXMMMSMMXAAXSAMMAMXMAXAMSAMMMSXSAXAMSSSMSSMXSAAMAMXAMMAMXSMXMSSMASAMMAAXAMSSSMSXMAXMASAMMSMMAMXXAS\n" +
                "AMAMMXSAMAMAMMMSMMMAAXXXMMMSMMXMSAMMSSMAMMMMXAAAAXMSMXMAXMAXAAMXSMMSMXASXSXSXMXMMXXAMAMMSMAMASXMAXMXMAMSASAMASMMSMXMMXXXMAXMSSXMASAXXMAMXSAS\n" +
                "XXAXXASAMXSXXAAAAASXSMMMMSAAXMAMMAMMAAMASASASMSSSMXAMXSAMXSSSMSAMMMXSMXXAMAXMAMSMXSAMXSAAMAMXXXXMXAAMMXSMMXSAMXXAMASAAXMSMMMAXMSXMASMSMSMMAM\n" +
                "SMXSMASAMXMMMMSSMMMXMAMAAMXMAMMMSAMXSSMXSAMAXAXXMXSXSXMASAAAAAMMSASAMXSMAMAMASMAMXMASASXXMAXMMSSSSSMMSAMMAASXMXSASAXMMSXAXSMAXMMSMXMXAAAXMMM\n" +
                "SAAAMAMAMSAMAXMMASXMSSMMSMMXSXAAMAMXAAMAMAMSMMMMAAMMSASAMMSMMMMXSMMASAAXXXAMSAMAXASMMASASMSSSMAAXAAASMSSMMMSAMASMMXSAAMXMSXMMSMXAXAASXXMXMSS\n" +
                "SASMXASAMSAMXSASAMAMAXAXMASAMMMMSSMMSAMAMAMXMAAAMAXXSAMXSAAAAXSAMXSSMMSSMSASMMSMSASXMAMXMAAAAMMSMSMMMAAMXMAMAMASAAAMMMSAXMASAAMMXSMXSAMSMMAM\n" +
                "XAMMSMXMMSAMAXXMAMSMMXMMSAMAXMAXAAAXMMMSAMXMXXSSSSMAMXMAMMXMMMMASMMMAAMAAXXSXXAMMAMXMAXAMSMSMMAAAXMMMMMSMSMSSMXSMMSSMASASXSMMSXSAXXAMAMAAMAM\n" +
                "MXMAAAXSAMAMSSSMSAMAAXMASXMMAMXMSSSMSXAXAMXSAMXXAAMSSMMSSMSSSMSAMAASXMSMSMMMMMXSMMMMSMSMMAXAAMSSSSXSAMAAAAXAAAMXMAAAMXMAMXAASAAMMMMXSMSSSMAS\n" +
                "AXMSMXMMASMMMAXAMASMSSMASXMSXXXMAMXAMMASXMAXMASMMXMAAXAMAAAAAXMASXMMAASAAAXAAXAMAMXAAAAMMMXSSMAXAXAMAXSMSMMSSMMAMMMMMXMSMMSMMMSMSXSAMXAXAMXA\n" +
                "SAMAMSAMAMAASXMXMAMXAAMAMXAAMSMSMMMMMMAMXMXSXSXAASMSMMXSAMMSMMSAMMASMMMSMSMSXSASAMMSMSMSXXMAMXMXXMMMAMMAAXXAMXSXSSSSSXMMAMMMAMAAAAMASMMXXMAX\n" +
                "MMSAMMAMXSSMMAXXMXSMSSMSSSMSAAASXAAAXXASXMAXXAMMMSAXMMAXXAAXMMMAMMAMASAXXXMAMXASXXMAAMAXASASXSXSAAXMASMSMMSXMXMASAAAMAMSAMAMAMMSMXMMMMSMSMSM\n" +
                "MAMMSSMMXXMAXXMXAXSAMXAXAXAAXMSMSSMMMSXSAMSSMMXMAMAMAMAXMXAMXMMMMMSSMMASMSSSMMXMASXMXMSMXMAMAAAXSMMMAMXAAAMMMMMSMMMMSAMXASXMXSAMXAMAAXAAAAAX\n" +
                "MMMAXAASXXSAMSMAXXXSSSSMMMXMXXXAAMASAMMSAMAAXXAMASASMMSASAASXSMSXMXAXMAMMAAAAASMXMAMXMASMSXMMMSMXMMSSMSSMMXAMMXAXXAXMXSSMMMAAMAMSSSXSSMSMSMS\n" +
                "SXMMMXMXAXMASAAMAMMMMMAAXAAMXMMMMSAMAMASAMSSMSXSASXSAAXAXXSAAAASAMSXMMMSMMSMMSMAASAMXMAXXAXXXAAMXAAAAAXXXAXXSSSMSSMSXXMASAMXMSAMSMSMAAMMXMAA\n" +
                "MAMXMMXMXMMXSASMSXAAAXSMMMMMAAAAAMXSAMMXXMAXASAMASASMMMMMMAMSMMXAMSMMXMAXMAMMAMSMSMXXMMMMMAMMMSSSMMSSSMMSMSXAAMXMAXAXMXMMMSAXXAXMAMMSMMMAMXM\n" +
                "SAMASAAMASMAMAMXMASXXMAXMASMMSMSXSASASXSSSMMXMAMAMMMXXXAAAMXXXSMSMSASXSXSXMXMAMXMXMASMSAMXAAXSAXMXMAXXAAMAAMMMMSSXMMMSAAAASXSSMMMAMXMMAXMMAX\n" +
                "SASXSMMSAXSAXAMXXAAAMSMMMAMAXAAMAMASASAAMAMMMSAMXSXSXSSSSSXSSMMAMAMSMXSAMXXSSSXSASAMMAMXSSMSXMXMSAMMMXSMMMMMAMXMMMAAASXSMXSXXAMASASASMSMSSSS\n" +
                "SXMASMMXAXXXXSSXMMMSAAMAMMSSMMSMAMXMXMAMSAMAAMASMSMSAAAAAXMXMAMMMSMMMAMAMMAMAAAMMSAMMSMMAXMMMMMXSASXSAMXAAASAMXAAMMMMSMXXXMMSAMMMAXASAAAAAAS\n" +
                "MAXAMASXMMSMMMXXXXAMMXMSXAAXXAMMMMAMXSXMXMSMMSAMAMAMMMMMMMMAXSMXAXAAMXMSXSXMMMMMXSAMAAASAMXAAAMASAMAMAMSXXASASMMMSAAXMASMMSASMMMMSMMMMMMMSMS\n" +
                "SMMMSAMMMAAMASAMXMXSSMMXMMSXMASAXMASAMMSXXSAAMAMXMAMAXSAXSSXSAXMASXMSSMMASMMXXXXAMMMMSMMASMSSSMMSAMMMSMMSSXMAMXAASMSMXMAAAMAMSASAMASAXXSAMAX\n" +
                "AMAMMMMMMSMSXSAMXMAMAASMSMAMSSMMMSAMXSAMXAMMMSSMMMAXMSMMSMASAMXMMXMASXASAMXXAMMSXMASXXXSAXMAMXMMSAMXAXAAXXXMAMMSMXXMMASMMMMSAMXMAXAMSSXMAXSA\n" +
                "MMXXAAXXMAMMXXXMAMAMMMMAAMAMXAAAMMXMAXASMMXAMXMMASMXMAMXAMMMXAMXMAMMMSXMASXMASAAAMXSAXAMASMMMAXXSXMMMSMMSMXSSXAXSMSMSAMAXXXXXMASAMXMAMXMAMMM\n" +
                "XMASMSSXXMASAMSSXSXSMMMSMMMSSSMMSXMASXMXMMSMSMXMXSMAMASXMSXSXSSSMMSSMMMXMMXXAMXSMMSMMMXMAMASMMSMMXXMAAAXAAAAXMAXAXAAMMSSMSMMMMMMXSXAMSMMMSAS\n" +
                "XSASXAXMSXAMASAAXSASXXXAMAAXAMXMSAXSAXAAAMAXSAMSASMSMASMAAAMAMAMSMAAAMAASMSMMSAMAXXAAXXMMXXMAMSAMXMMSSSMMMMXXMSSMMMSMMXMASAAAXAAAMMXMAXMXSAS\n" +
                "XMASAMXAXMSSMMMSMSAXMXMAXSSMMMSXSAMAMSMMSMSMMSMMASAMMMMMAMSMAMMMAMSSMMMMSAAAMMXSXMMSMSXMASXSMMSSSXXAAAXAMXXMSAMAXMXMMSMMSMSMSSMSMAAMSXSXAMSM\n" +
                "MMAMMXMXSAMAAMXXAMMMAASMMAMAXAMMMXMAXAAMMMXAXXXMAMXMAMXXSSXMXSXSMMXAXAXMMMMXMXMMMMAMXXMASXXAAASXMASMSSSMMMAMMASAMMMXAAMXMAMXMMMAMXXMXXAMMSAX\n" +
                "AMAMSASXAXSSMMMMSMXXSXAXMAMMMMSXMAMXMSSMSASAMXXMXSAXAMXXXAXAMXAMXMXMMMXSAMXMSMAAAMASXMSMMMSSMMMAAXMAMAMXASASXMMAMAAMSXSASAMAXXMAXSMMMMSASMMM\n" +
                "SXSXSASMXMXMAAXAXASMXMMASMXSAMXXMAMAXXAAMXMAAMAMASMSMSAMXMMSAMXMAMAXMAMSAMMAASMSMSXSAAAAAAMMSXSXMASXMSMSMSASAMAAMMXXMASAMASXMSSMMSAAAAXMSAAM\n" +
                "MAMAMAMAAMXSSMSMXAMMAMXMAAMMMXMAXXSMSSMMMAMXSSXSAXXAAMAMXMAXAMMMXSAXMMMSMMSSXXXAASAMMSSSMSAAAXSAMXSAMAAAAMASAMSXSXSSMMMSMAXXAAAMAMMMMMSASMMS\n" +
                "MAMAMXMSXXAMMASMMSMXASAXMMMASASAXMAMAXAASMSAMXAMXSSMSMAMSMMSAMAAXMXMXMAMXAAXXSAMXMAMAXAXMXMMXXSAMMMASMAMXMAMAMMAXAMAAXAXMMMMXSXMASMXSAMXMAMA\n" +
                "MASMSSMASMASMAMAAXMMAXMXMASMMASAXSAMASMMSMAMMMXMAXXAAMAMMAXSASMXSAXSXMSMMMSMSASAXMAMMSMSMXSSXASAMXSAMXAXXMAMMSMMMAXXMMSSMAXXAXXSXSAAMMSASAMM\n" +
                "SXXMAMMASMSMMMSMMMMMSMMASXSAMMMMMMXMASAMXMAMXXSSSSMSMSMSMMMSXMASMXMXMAAAXAAMSAXMASAXXAXAMSAMMMMMMXMASXXSXSASMAAMSMMSSXMAXXSMMXASASMXMXSMSXSA\n" +
                "AMSMASMASMMASMSXSASAAASMSAMXMXAAXXAMXSXMASXSXMXAAAAXAAAAAXAXAMMMMAMAMSSSMMMXMAMMMSASMMSMSMAXXXMAMXXMMXAMXSMSMMXMAAMXMASAMXMMSMAMAMMSMASXMAMX\n" +
                "SAASASMAMAMXMAMAXMAXXMMXMAMAMMAMMSMSMMXSXSMMASMMMMSMMMSMSMMSAMXAMAMXMAXAXSSMAXMXMXXMAAXXXMMMMSSMASXMAXMAMMAXAMXSAMXAMMMAMAXAXMMMXMXAXAXAAMXS\n" +
                "MSMMSSMMSSMAMAMSMSXMSSMMASMXXMAAXAMXMXMXAXAXAMAAXXAASXMAXAXXXMSMSSSMMMMMMXAAMXSXSMASXMAMSASASAMAAXAMXXXMAMMMSMAMMMSMSMMSMSMMSMMXMMSMSMSXMXAX\n" +
                "MXXMAXMMAAXMMAMXAXAXAAASXMASMSXSSMSXMAXMSMSMSSSMSSSXMAMXMXMAAXSAAXAMAXASXSMSMXSAMSXMASAAXAXMMASMXXAMAMSMSAXAXMMMAAAAAAMXAXAMAXAAAXAAAAMMSMMS\n" +
                "AXSMSAXMSSMSSMMMMMXMMSMMAMAMAAAXAMMASXSAAAXXMAMAMAXSSXMASXMSMAMMMSXSSSMSAAXMMXMAMAMSAMMSMXMXSMMAMMAMASMAMMMMXMASMSXSXSMMXMSSSSSSSSMSMSMAMAMA\n" +
                "MAXXMAXXAMXAAASAMXXAXAAMXMSMMMMMAMSMXMAXMSSMXAMXMAMMMAXAXAXMXMSAMXAMXAAMMMXMXMSXMSAMAMAXAMAMMAMAMSMMMXMAMXMSAMMSAXXAAXXMAXXXAAMMMAMMMMMXSAMA\n" +
                "SMMMSAMMASXSSMMAAAMMMSSMXMXXMAMSSMXSASAMXAAMSMSXMASMSSMSSMMSAMAMXMSMXMMMXMMMAMSAMXXAAXMXSASASMMXMAMAXMMSSSXAMXMMAMMSMXASXSSMMMMAMAMXAASMSMSX\n" +
                "XAAAMXXXMXMAXMSMMMXSAAXMXXMAMAMAAXAMXMASXSMMAMAMSASMAXAAAASXXSMSAMXAASAXAMAXXMMASAMXSAXAMMMMXXAXSASMMSAMXXAXMASMMMAXXSAMXAXXXASMSMSXSMSAMASM\n" +
                "SSMSMSXSXSMSMMXXSAAMMMSMXMSMMAMSSMMSSSMMAXXMAXAMMXSMAMXXAMXMXXMAXXMXMXASMSSMSASASASAAMMXSMSXXMXMMAMXAMMSMMXMSXSAMXSMASMMMMMXSAXAAXXMMMMMMAMA\n" +
                "XMAXAMAXMAMAMSSSMMMXSMMMMMAMSXMXAAXAAAXMXMXSASMSSMSMAMSMXSAMXAMSMSMXSXMXAAAASAMASMMMSXSXSAXXXAMSMXMMSMAAAMMXXASMMMXAXSASAASMMSMSMMMXSASXMASM\n" +
                "MMAMAMMMXSAMXAMXAXSAXAMXAMAMMASMSSMMXMMXAAXMAMMAAAXMMXSAASMSSXMAAXMASAMMXMXMMAMAMXSXAASAMMMMXMMSASMAMMSSSMAAMAXASXSSXSAMSMSAAAMAAXMASXMASAXA\n" +
                "AMAXSMXMAMMMMSSSMMAXXAMSSSMXXAMXAAAXSSMSXSAMAMMSMMMXSAMMMSAMAMMXSAMASAMAMSSSSXMASASAMXMXMAAAMSAMXMMXSAAXMASXMMXMMAMAAMMMXXSMMMSSSXMMSMSMMMSX\n" +
                "SSMSMAXMAMXAAAMAMSAMSAMMASAAMSSMMSSMAAASAAMXXXAAAXXXMAXXXMMMMMSMXAMXSAXMAXAAMXXAMXSMMAAXMSMSSMXSXXXAMMMSXAMAAMSSMAMMXMASMASMMMXAMMSXSMAMAXAM\n" +
                "MMMAMMMSSSXMXSMAMMAXXXMMAMMMXXAAAAAASMMMXMXSSMSSSMMMSAMXSMMASXAAMMXAMMMMXMMMMSMXXXXAXXSSXMAXAMSSMMMXXAXMMXSSMAAAMXXXXSASMMXAAXMXMAMXXMASMSMA\n" +
                "XASXSXMAMMAMAXMASMMMMSXMXSXSXSSMMSSXXXXXMXAXAAAAMAAXMASMAXSAMMXXASMSXSASAAXSASASMMSSMXAAAMXMAMAMAXXAMSXSAXMMXMSMMSXMXMAMXXSXMSSMMSSMMSMXXAXM\n" +
                "SMMMSXMAXSMMASXMSAMAXAAXMXAAXXXAMXMMMMSSSMSSMMMSMSSXSAMMMMMASMSMSMAAASASASXMASXXAXAAMASMSMASMMASMMMXSAASMXAAXMAXAXAMMMSMSMSAMXMAMXAMXAAMSSSS\n" +
                "AXAAMASAMMXMXMAMXMSSSMMMAMXMMXSXMAAAASAMAAXXMAMAMXMXMAMAMAMMMAAXASMMMMAMAXAMXMAXMMXSAMAAAXXXASAXXAXMMMXSAXSMXSAMSSXSAAAXSAMXSXXSMSMMSMSMSAAX\n" +
                "SSMXSMMASMAMMSSMXXAXXAAASAXXAMMMSSSSXMASMMMXSSSSMMXSXSSMXAXSMMMSASXMAMMMMSXSXSMSXMAXMSMSMSXSXMASMSSSXMAMMMXAMSASMXASMSSXSASASAAAAAMMXAMMMMMM\n" +
                "MAXXAXSAMMAXMAXMMMMSSSXSAMXSXMXAAMMMMSMMXMSAMMAMXSMMAMAASXSMAAAMASASMMMAAXXMAAXAAMASXMAXASMSASXSAAAAAMAMAAMAMSMMMMMMXXMAMAMASMMMSSSMMMMASXSX\n" +
                "SAMMAMXXSSSSMAMMAAAMXAXMXSASASMMSMSAAAMXSXMASMSMAMAMSMMMXMAXSMXSASMMSSSMXSAMAMSSSMASXMMMMMAMAMAMAMMMMSSSMSSSMSAMXASXSAMMMSMMMXAXAAAMASXMMAAS\n" +
                "MASXMMXSAMXAMSMSXSMSMSMMAMMXAMAAMASMSXSAMASXMAMMMSXMXXXXMSAMXXMMMSXAAXAAASAMAXMAAMAXXMAAAMSMAMMMSMXXXXAAXMAMASXMSXSAMXSAAAAXAASMMSMSAMAAMXMX\n" +
                "XMXAAAXXSMXAMXAMAXXMAMAMAXXMSMMSMAMXMMMMXAMXMXMAMMAMMXMMAMXMMMXAAXMMSSSMMSMMSSMMMSSMASASMSMXXSAAAXXMAMSMMMAXMXMXSMMMMAMMSMSMSSXMXXAMMMSMMAXX\n" +
                "SMSMMMXXAXAXAMMMAMAXSSXMAMSAAAAXMXSAMAMSMSSSMMSSXMAAAAMMAMAAAMXMXXMAMAAMMXMAXAMXXAASXMAMXAXXXSMSSSXSAAAAXMMSMAMSMMAMMAMXMAXAXMAMASMMSAXXSXXX\n" +
                "AAAXMASMAMSSSMXMASXMAMMMAAMXMMMXMASMAAAXXAAASAMAASXSMMSASMMXAMASASMSMSMMSAMMMMMSMSXMSMSMSMMAMXAXAAASXXMMMAMAMMMAXSASMMSAMAMMMSXMASAAMMSMMMSM\n" +
                "MMMSMASMAMMAAAXSAXXAAXXMMSMSXXMXSAMXSMSAMXSMMSXSXMAXAAAMMMMMAMASASAAAAAASMSSSSXSAXXXAXXAXSXMAAXMMMMMXSSMSAMXSSSMXSASAAMXMSSXAMXMASMMXMAAAAAX\n" +
                "ASAXMAMMMSMSMMMMASMSMXXXAAXXMASXMXSMXMXAMXXXMAXXMMXMMMSXMAMSSMXMXMMMSMMMSAAAAAAMMMASMMMMMSMXMMMAAXAMAMAASASMMMAXAMMMMMMMXAXMAMSAMXASASMSMSSS\n" +
                "XAXXXXMAXSMXMMMMMMMAMXXSSSMMSSMAMMSAAMSSMMXSAMXSAASXSAMAMMMAAMMMMMAXMXMAMMMSMMXMAMMXAAAAMXAMXSASXSMMMSAMMMMAASXMSXSAXXASMMSXSAMMMSXMASAMAMXM\n" +
                "MMSSXASXXMMAMAMAMXSXSSMXAAAASAMXMAMSXXAAASAMAXASXMAAMAXAMSMSSMAAXSAMMAMXSXMAXMSMSSXSXMXMSMMMAXMAMAAAAMMMAXXXMMSAXASMSSMMAXAMMMMAAMAXAMAMXXAM\n" +
                "MXAMMAMXASXXXASASMMMXMAMMMMMSAMXMSMMSMMSXMASXMMSXMMSMMXSMXAAAXSSXMMXSAMMMASMMMAAASAMXSAMAAAMXSMMXSMMSSSSSSMMSAXSMMMMMAASXMMMSASMSSMMSMMMSMAM\n" +
                "XMAXMAXMMMASMASASMXAAXSMXAXAMXMASXSAASMXMSXMASAMAAXXAAAMXSMMSMMXAAAASASXSXMAMSMMMSXMASASXSXSXXAMXMAMMAAXAAAAMAXAMAAAXMMMSAXAMXMAXAAAXAMAXMAM\n" +
                "MSSXSXSAAAAMMAMXMXSSSSXAXMMSXXXXAXMSMSMMAXXMAMASMMMSMMXXAXASXMSSMMMMSMMMMXMAMMASAMAMAMAMXMAMAMSMMMAMMMMMSMMMMSMMSSSSMAAAXSMMSXMXSXMASAMXSXXX\n" +
                "MAMXSAMMSMSSXAXMAXMAMMXXMXMXAMSSMXXAMXAMSMSMASAMAAAXMASMMMSMSAAXMAXXSMSMSAMMMSAMASXMAMSAAMAXAXMXMASMXXAAMMASAXMXAMAAMSMSSXXXAXSXSXSXSAMAMMXS\n" +
                "MASMMAMAXAAAMSXSXSMAMSMMSXSMAMAAXXXASMSMAASXMMMSSMMSMAXAXXMAMMMSSMMMXAAASAXSAMXSXMAMAAMXXSSMMXSAMAMASMMSMXAMMASMMMSAMXXMAMAMMXXAXAMAMXMXSAXA\n" +
                "SASASAMMSSMMXXAAASXXSAAAAAMSMMXXXSSMMMASMSMASXMAAAAAMSXMMMMAMAXAAASXMMMXMAMMAMXXASXMMSXSXAAAXMSAMAMASXMAXMXSXMSAMAMMXSMSAMXAXAMSMSMMMAMXSMSM\n" +
                "MASAMMSMAXSXAMMMMMASXMSMMSMSMMMSMMASXXAXMAMXMXMSXMMSAMXSAXMASMMSMMMAAXMSMMMMXMMMMMMXXAAXMSSXXAMAMXSAMASASMMMAMSMMAXXSAAMASXMMXSAAXMXMASAMXXM\n" +
                "MXMASAAMSSSMAMXSSMMMMAMAXXAXXAAAASAMXMAMSASMMXMMXSAMXXXSASXMSXAXAASXMMAAAAAMSXSAAMAXMMSMAXMASMXSMXMXSAMXSAASAMXXSMSMMAXSAMMSSXSMSMAAMMMXSMMS\n" +
                "MSMMMXSSMMMXSXMSAMXMMASMMMMMSMMMXMASMXAMMAMXMMSAAXMAMXMMMMAMMMSMSMSXMXSMXMXXAAMSXSXAMAMMMMMMAAAXMSAXMMSASXMSAMXXMXXXAAMMASAAMAMAXXSMSMAMXXAX\n" +
                "XAAMAMMXXAAAXAMXSMAXSASAMAAMAASMSSXMASASMSMAXAMMSSMSXMSAXSMMAAMAXAXASXXMSSSMMSMMMMMSMMMSAAXSMMMMAXSAASMASMXSXSSMMMXMMSSXAMMAMSMAMAXAAMMXMMSS\n" +
                "SSSMASMMSMMMSAMSMXMMMASASMMSMSMXAAXAXAMXAXSMMSSMMAAAAMXSMAMMMSSSMMMXMMAXAAXMXAXSAMXXASASXMMMASXXMAMMXMMMMMMMXXXAAXAXAMMASXSXAXMXMAMSMSMMSAMX\n" +
                "AAAMXMAAXAAXXAMAAAXAMXMAMXAMXMAMMMMSAAXMXMAMAXAXSMMMXMAXMAMXAAAMXSSMSSSMMXMSSMSASXMXAMASASXSMMSAMAXMSSMAAAAMMMSSMXSMSXSAMXAXMXSMMSXXXXAASAMX\n" +
                "MSMMXSMSSXMMSSMMSMMASMMSMSSMMSAMXAAXMAAXMSMMSSMMSMASAMXSSMSMMMSMAMMAAAMASMXAAXAMAMAMXMXSMSXAAASXSSSMAMXSSMSAXAAAXAXAXXMASXSMMASAXMAMXSMMSAMX\n" +
                "XXXSMAXXAAMXAMXXMXASXXMAMXAAASAMSMSMXSSSMAXSXAAMXSASAMAMAMMAMSAMXSMMSXSAMAMSSMMXAAMAASXSXXMSMMMMAMXMASXMAAAMMSSSMMMAMASAMMXAMAXXMASMMSAASAMM\n" +
                "XMAXAMSMSMXAXAASMMMXAXXAMSSMMSAMXXMXAMXAXAXASMMSAMMSAMASAMSAMXAXMXAXXAMXSSXXXAXSMSMSMSASXXAXMXMASXXMMMAMMMXXXMAXAXMAMAMXMASMMXSSMAAMASMMSMMA\n" +
                "SMMMSXAAAAXMSAMXAMXMAMSMXMAAAMMAMXMMMSSMMMMMXXAMASASXMXMXMSXSSSMAMMMMMMAMMSAXXMXAMMMAMXMAXSASMSMMXXXSSSMXSXMXXASXMSAMXSSSMMXSXAAMMMMASAASMMS\n" +
                "SAMXASMSMSXMAMMXXMAAAAAXAXXMMMXMMMSAAMXMAXSXSMSSSMMXMSSSMXSAMAAXXXAAXMMMMAMXMSSMMSMMAMAMXMXASMASAXXXMAMMAMMMMXMAMASASAXMAASAMMSMMAAMMSMMMAXX\n" +
                "SAMMMMXMMXAASMSMSSMSMSMSMSSSMSMSMASMXSAXAMSASAAXMAMSAMSASAMMMSMSXSSSMMASMAMAXXAAAAXMASXMSXMXMMAMMXAMMMMMXXAAAAMAAXSMMXXXSMMASMASXSXSMXMASMMM\n" +
                "SMMXAAAMXSSMXAAAAMMAXAAAAAAAAAAAMMMSMSAMSMMAMMMXSAMASMSXMMSXAAAXAMXXASASXASXXSSMMASXXXMXMAMMMMXSXXMSAXXXXSSSSXSASASASXXMASXXMXAXXAASAXXMAMAM\n" +
                "MAMSMSMSAMXSMMMMMSXMSMSMMMSMMMSMSAAAMMAMXASXXSXAMASMMXMSXXAXSMMMXMASMMMMMXSXAMXMMAXXXXMAMAMAMXMAMAMAMSAMXXMAXAXAMAMAXAXSAMMAMMXSMMMMAMSSSSMS\n" +
                "MAMXMAXAMSAMXSSXXXAXSAMXXMMMMAAXSMSMMSAMSAMAXMMXSAMXMMMSXMMAMXSMAMAMAAMSMMMMMMASMASXMMSAXSSMSAASXSMAMSMSMSSMSMSAMXMMMSMMXMXMXSAAMSAMXMXAAMMM\n" +
                "SSXSMSXMMMMSAMXASMMMMAMSAMXASMMXXAXXXSSMMAMXMSAMXMMASAASASXMSAASXMXSSMMAAASAXXAMXSAMXMAMXAAASMMXAXMSXMAAAXAAAAMXMAAXAAAMSMXSAMSSMMMXAAMMMSAS\n" +
                "XAASAXXXAXXMMMAXXMSAMXMMASXMSAMMMXMMMMMXMXMAMMAMMXXAMMMXAMMXSMMMXMMAMXSSSMSASAXXXMXAXSASMXMMMMAMMMMMAMSMMMMMMSMAMSSMXSXXAAXMAMAMMASAMXSXXSAS\n" +
                "SMXMASASMSMAXSMSXMAMSAMSAMMASXMASAAXSXMSSSMAXSAMASMSMSSMAMSMMSXAAXSMMXAAXXMAMAMSSSSXMMAMXSMSMMAXAAASAMXMSAAAXXXXMAXXAXXSMSMSMSAXSASAXAMAXMAM\n" +
                "AAXMSMAAAXMXMASMASAASAMMSSMAMAMAXMXMMAAAAXMAXXMXMXAXAAAXMMXXAMXMMXMAMMMMMMMMMSMXAAAASMMMSAAXXSMSSSMSXSAXASXXMSXSAXXMMSAMAMAAASAMMASXMMMSMMMM\n" +
                "MMMMXMSMMMSAXMASAMSMSXMAAXMAMSMSSSXAMMMMSMMSMSSSSMMMMMSXSASMSSSMSASAMAAAAXMAAMAMXMSAMASXXMMMMMAAAXAMAMMSMXSAAMASXSMXAMMMAMSMXMAMMAMXASAMAMAS\n" +
                "XAAXAAAAAAMSSSMMXXXXXAMXMMXASMAXAMXSAMXXXAMXAAAAMAAXXAXMMASAMAMXSMXASXSSSSSMXSASXXMAMAMXAXMAAAAMMMASMMAAXAMMMMAMASASXSMSMMAXSAXMMASXXMASAMAX\n" +
                "SSSSMMSSMXSAXXXXMMMSMMSAXSMXAMXMAMAMASXSSMMMMMXMXSMSMMMMMAMAMAMXMXSMMMAMMMMAMSASXSMXMASXSMSXXSSXXMXAXMASMSSSMMASMMAMAAAASAMXMAAXXMAXXMASAMMS\n" +
                "AAXAMXXAASAMXMMSAXAXAASAMXMAASXMMMXSAMMMAXXAAMASAMXXAAASMMSXSASMMAXAAMMMAMMAMMAMAAXASXSAMXAMMMMMSMSMMMMXMMAAXSMSAMXMSMMSAMXXMAMXXMASXMXSXMSA\n" +
                "MMMMMXMAXAMXMSASMMMXMMSMMAXXMMAAXAAMAMMXMMSSMSASAMMSMSMSAAAXSAMAMAXSMMXSAMXAXMAMXMSASAMXMMASAAAAAXAXAXMASMSMMSXSMMXMXXXMASXMXMSXSMASASAXMXXM\n" +
                "MSAAXSMMSAMAMMAMXAMAXASAMMXSAMSMMXMSSXSASMMAAMXMAMAAAMXMMMSMMAMSMSXMASXSASMMXSASMXMAXMAMXMASMSMSSSMXSASASXMAXXMXMXMASXSMAMAXMASAAMXMMMAMSMAX\n" +
                "SSMSXSAAXXMASXSXSASMSASAMAAMAMMMSXXXAASAMXMSMMSSMMXSAMAXSAMXMMMXAXASAMAMXMAMAMMMAXMAMMAMAMMSAXXMMXXAXXMAMXMSSSMSXXAAXXXMASXMASMMMSSMXMSAASXM\n" +
                "XXAAMMMMSMSASAXAMAAXMASAMMSSMMMAMAMMMMMAMXAMXAAAAAMMAMXXMASXMMSMXMASAMXMASMMMSSSSSMAMSASXSSMMMASASASMSMSMSAAAAAMMMMMSMMMASAMSXAXAAXMAAXSMSXM\n" +
                "MMMMAAAXAMMASMMXMSMSAMXXXXAAASMAMXMASXSSMMSMMMSSMMMSAMSXSAMXAAAAASXSAMXSASAAXAAAAAXAMSAMAMXAMSXMASAMSXAAAMMMSMMMAAAXXMASXSMMASMMMSASMSMAXMMS\n" +
                "XMMXSMSMMSMAMXXXXXMAMSAMXMSSMMSMSASMSXXAXAXXMAXXMSAMXXXXMASAMSMSAMXSXMAMXSXMMMSMSMMMMMAMAMSSMMMMAMAMAMSMXMXXMXMASMMSAMXAASAMXSXXXXMXAMMAMXSX";

        for(int i = 0; i<inputString.length() ; i++){
            if(inputString.charAt(i) == 'X'){
                if(checkIfXMASBefore(inputString, i)){
                    counter ++;
                    System.out.println("before");
                }
                if(checkIfXMASAfter(inputString, i)){
                    counter ++;
                    System.out.println("after");
                }
                if(checkIfXMASDiagonalDownRight(inputString, i, lengthOfLine)){
                    counter ++;
                    System.out.println("downright");
                }
                if(checkIfXMASDiagonalDownLeft(inputString, i, lengthOfLine)){
                    counter ++;
                    System.out.println("downleft");
                }
                if(checkIfXMASDiagonalUpRight(inputString, i, lengthOfLine)){
                    counter ++;
                    System.out.println("upright");
                }
                if(checkIfXMASDiagonalUpLeft(inputString, i, lengthOfLine)){
                    counter ++;
                    System.out.println("upleft");
                }
                if(checkIfXMASUp(inputString,i,lengthOfLine)){
                    counter ++;
                }
                if(checkIfXMASDown(inputString,i,lengthOfLine)){
                    counter ++;
                }
            }
        }
        System.out.println("Lösung: " + counter);
    }

    static boolean checkIfXMASBefore(String inputString, int index){
        if(inputString.charAt(index-1) == 'M'){
            if(inputString.charAt(index-2) == 'A'){
                if(inputString.charAt(index-3) == 'S'){
                    return true;
                }
            }
        }
        return false;
    }

    static boolean checkIfXMASAfter(String inputString, int index){
        if(index+3 < inputString.length()) {
            if (inputString.charAt(index + 1) == 'M') {
                if (inputString.charAt(index + 2) == 'A') {
                    if (inputString.charAt(index + 3) == 'S') {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    static boolean checkIfXMASDiagonalDownRight(String inputString, int index, int lengthOfLine){
        if(index+ 3 * lengthOfLine + 1 < inputString.length()) {
            if (inputString.charAt(index + lengthOfLine + 1) == 'M') {
                if (inputString.charAt(index + 2 * lengthOfLine + 2) == 'A') {
                    if (inputString.charAt(index + 3 * lengthOfLine + 3) == 'S') {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    static boolean checkIfXMASDiagonalDownLeft(String inputString, int index, int lengthOfLine){
        if(index+ 3 * lengthOfLine - 1 < inputString.length()) {
            if (inputString.charAt(index + lengthOfLine - 1) == 'M') {
                if (inputString.charAt(index + 2 * lengthOfLine - 2) == 'A') {
                    if (inputString.charAt(index + 3 * lengthOfLine - 3) == 'S') {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    static boolean checkIfXMASDiagonalUpRight(String inputString, int index, int lengthOfLine){
        if(index - 3 * lengthOfLine + 3 > -1) {
            if (inputString.charAt(index - lengthOfLine + 1) == 'M') {
                if (inputString.charAt(index - 2 * lengthOfLine + 2) == 'A') {
                    if (inputString.charAt(index - 3 * lengthOfLine + 3) == 'S') {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    static boolean checkIfXMASDiagonalUpLeft(String inputString, int index, int lengthOfLine){
        if(index - 3 * lengthOfLine - 3 > -1) {
            if (inputString.charAt(index - lengthOfLine - 1) == 'M') {
                if (inputString.charAt(index - 2 * lengthOfLine - 2) == 'A') {
                    if (inputString.charAt(index - 3 * lengthOfLine - 3) == 'S') {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    static boolean checkIfXMASUp(String inputString, int index, int lengthOfLine){
        if(index - 3 * lengthOfLine > -1) {
            if (inputString.charAt(index - lengthOfLine) == 'M') {
                if (inputString.charAt(index - 2 * lengthOfLine) == 'A') {
                    if (inputString.charAt(index - 3 * lengthOfLine) == 'S') {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    static boolean checkIfXMASDown(String inputString, int index, int lengthOfLine){
        if(index + 3 * lengthOfLine < inputString.length()) {
            if (inputString.charAt(index + lengthOfLine) == 'M') {
                if (inputString.charAt(index + 2 * lengthOfLine) == 'A') {
                    if (inputString.charAt(index + 3 * lengthOfLine) == 'S') {
                        return true;
                    }
                }
            }
        }
        return false;
    }
}
